import { auth0 } from "@/lib/auth0";
import Container from '@mui/material/Container';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AppBar from "./AppBar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth0.getSession();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Container className="h-screen w-screen items-center justify-center flex">
          <AppBar session={session} />
          {children}
        </Container>
      </body>
    </html>
  );
}
